---
kind: Namespace
apiVersion: v1
metadata:
  name: crbot
  labels:
    name: crbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crbot-deployment
  namespace: crbot
  labels:
    app: crbot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crbot
  template:
    metadata:
      name: crbot
      namespace: crbot
      labels:
        app: crbot
        department: bots
    spec:
      containers:
        - name: crbotcontainer
          image: ghcr.io/theyellow/cr-discord-bot:main
          envFrom:
            - secretRef:
                name: crbot-secrets
          ports:
            - containerPort: 8080
          command: [ "java", "-Xmx300m", "-jar", "/crbot.jar" ]
---
apiVersion: v1
kind: Service
metadata:
  name: crbot-service
  namespace: crbot
spec:
  selector:
    app: crbot
    department: bots
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31080
---
