---
kind: Namespace
apiVersion: v1
metadata:
  name: crbot
  labels:
    name: crbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crbot-deployment
  namespace: crbot
  labels:
    app: crbot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crbot
  template:
    metadata:
      name: crbot
      namespace: crbot
      labels:
        app: crbot
        department: bots
    spec:
      containers:
        - name: crbotcontainer
          image: ghcr.io/theyellow/cr-discord-bot:main
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: crbot-secrets
          ports:
            - containerPort: 8080
          command: [ "java", "-Xmx300m", "-jar", "/crbot.jar" ]
---
apiVersion: v1
kind: Service
metadata:
  name: crbot-service
  namespace: crbot
spec:
  selector:
    app: crbot
    department: bots
  type: NodePort
  ports:
    - port: 6379
      nodePort: 32379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crbot-redis-config
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis:5.0.4
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: crbot-redis-config
        items:
          - key: redis-config
            path: redis.conf
---
