# Redis deployment configuration for Kubernetes
#
# This YAML file sets up a Redis instance within a Kubernetes cluster.
# It includes the namespace, service, configuration, and pod specifications.
# Port-mapping is internal:6379 -> external:30379
#
# To deploy this configuration, use the following command:
# kubectl apply -f redis.yaml
#
---
# Define the namespace for the Redis components
apiVersion: v1
kind: Namespace
metadata:
  name: cr-discord-bot
  labels:
    name: cr-discord-bot
---
# Define the service for Redis
# This service exposes Redis on port 6379 internally and port 30379 externally
apiVersion: v1
kind: Service
metadata:
  name: cr-discord-bot-redis
  namespace: cr-discord-bot
spec:
  selector:
    app: cr-discord-redis
    department: bots
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30379
---
# Define the configuration for Redis using a ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: cr-discord-bot-redis-config
  namespace: cr-discord-bot
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    pidfile /data/redis-6379.pid
---
# Define the Pod that includes Redis
apiVersion: v1
kind: Pod
metadata:
  name: redis-discord
  namespace: cr-discord-bot
  labels:
    app: cr-discord-redis
    department: bots
spec:
  # Initialization container to configure system settings
  initContainers:
    - name: system-init
      image: busybox:1.32
      imagePullPolicy: IfNotPresent
      command:
        - "sh"
        - "-c"
        - "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - name: sys
          mountPath: /sys
  # Main container running Redis
  containers:
    - name: redis-discord
      image: redis:5.0.8
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.2"
      # Liveness probe to check if Redis is running
      livenessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 300
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      # Readiness probe to check if Redis is ready to serve traffic
      readinessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: cr-discord-bot-redis-config
        items:
          - key: redis-config
            path: redis.conf
    - name: sys
      hostPath:
        path: /sys
---