# Redis deployment
#
# port-mapping is internal:6379 -> external:30379
#
# For deployment use:
# kubectl apply -f redis.yaml
#
---
# namespace "cr-discord-bot" for kubernetes components of cr-discord-bot
apiVersion: v1
kind: Namespace
metadata:
  name: cr-discord-bot
  labels:
    name: cr-discord-bot
---
# service for Redis
# port internal: 6379
# port external: 30379
apiVersion: v1
kind: Service
metadata:
  name: cr-discord-bot-redis
  namespace: cr-discord-bot
spec:
  selector:
    app: cr-discord-redis
    department: bots
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30379
---
# configuration for Redis
apiVersion: v1
kind: ConfigMap
metadata:
  name: cr-discord-bot-redis-config
  namespace: cr-discord-bot
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    pidfile /data/redis-6379.pid
---
# Pod including Redis 5.0.4
apiVersion: v1
kind: Pod
metadata:
  name: redis-discord
  namespace: cr-discord-bot
  labels:
      app: cr-discord-redis
      department: bots
spec:
  initContainers:
    - name: system-init
      image: busybox:1.32
      imagePullPolicy: IfNotPresent
      command:
        - "sh"
        - "-c"
        - "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - name: sys
          mountPath: /sys
  containers:
    - name: redis-discord
      image: redis:5.0.8
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.2"
      livenessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 300
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: cr-discord-bot-redis-config
        items:
          - key: redis-config
            path: redis.conf
    - name: sys
      hostPath:
        path: /sys
---
