# Redis deployment
#
# port-mapping is internal:6379 -> external:31379
#
# For deployment use:
# kubectl apply -f redis.yaml
#
---
# namespace "cr-discord-bot" for kubernetes components of cr-discord-bot
kind: Namespace
apiVersion: v1
metadata:
  name: cr-discord-bot
  labels:
    name: cr-discord-bot
---
# service for Redis
# port internal: 6379
# port external: 31379

apiVersion: v1
kind: Service
metadata:
  name: cr-discord-bot-redis
  namespace: cr-discord-bot
spec:
  selector:
    app: cr-discord-redis
    department: bots
  type: NodePort
  ports:
    - port: 6379
      nodePort: 31379
---
# configuration for Redis
apiVersion: v1
kind: ConfigMap
metadata:
  name: cr-discord-bot-redis-config
  namespace: cr-discord-bot
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
---
# Pod including Redis 5.0.4
apiVersion: v1
kind: Pod
metadata:
  name: redis-discord
  namespace: cr-discord-bot
  labels:
      app: cr-discord-redis
      department: bots
spec:
  containers:
    - name: redis-discord
      image: redis:5.0.4
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: cr-discord-bot-redis-config
        items:
          - key: redis-config
            path: redis.conf
---
