# RSocket middleware components (deployment with one pod)
#
# port-mapping is:
# for router internal:33331 -> external:30321
# for payload-server internal:33333 -> external:30323
# for shard-coordinator internal:33332 -> external:30322
#
# For deployment use:
# kubectl apply -f rsocket-middleware.yaml
#
---
# namespace "cr-discord-bot" for kubernetes components of cr-discord-bot
kind: Namespace
apiVersion: v1
metadata:
  name: cr-discord-bot
  labels:
    name: cr-discord-bot
---
# service for micronaut (external port 29121)
apiVersion: v1
kind: Service
metadata:
  name: state
  namespace: cr-discord-bot
spec:
  selector:
    app: cr-discord-rsocket-middleware
    department: bots
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30121
---
# service for rsocket-router (external port 30321)
apiVersion: v1
kind: Service
metadata:
  name: cr-discord-rsocket-router
  namespace: cr-discord-bot
spec:
  selector:
    app: cr-discord-rsocket-middleware
    department: bots
  type: NodePort
  ports:
    - port: 33331
      nodePort: 30321
---
# service for rsocket-payload-server  (external port 30323)
apiVersion: v1
kind: Service
metadata:
    name: cr-discord-rsocket-payload-server
    namespace: cr-discord-bot
spec:
    selector:
        app: cr-discord-rsocket-middleware
        department: bots
    type: NodePort
    ports:
        - port: 33333
          nodePort: 30323
---
# service for rsocket-shard-coordinator (external port 30322)
apiVersion: v1
kind: Service
metadata:
    name: cr-discord-rsocket-shard-coordinator
    namespace: cr-discord-bot
spec:
    selector:
        app: cr-discord-rsocket-middleware
        department: bots
    type: NodePort
    ports:
        - port: 33332
          nodePort: 30322
---
# deployment of rsocket-middleware ( micronaut-application in ./rsocket-middleware/ )
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cr-discord-rsocket-middleware-deployment
    namespace: cr-discord-bot
    labels:
        app: cr-discord-rsocket-middleware-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cr-discord-rsocket-middleware
    template:
        metadata:
            name: cr-discord-rsocket-middleware
            namespace: cr-discord-bot
            labels:
                app: cr-discord-rsocket-middleware
                department: bots
        spec:
            containers:
                - name: cr-discord-bot-rsocket-middleware-container
                  image:  ghcr.io/theyellow/cr-discord-bot-rsocket-middleware:main
                  imagePullPolicy: Always
                  envFrom:
                      - secretRef:
                            name: cr-discord-bot-secrets
                  ports:
                    - containerPort: 8080 # micronaut standard
                    - containerPort: 33331 # router
                    - containerPort: 33332 # shard-coordinator
                    - containerPort: 33333 # payload-server
                  command: [ "java", "-jar", "/rsocket-middleware.jar"]
---
