/*
 * Clash Royale API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package crdiscordbot.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * BattleLogTeam
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-01-09T15:49:55.865Z")
public class BattleLogTeam {
  @SerializedName("tag")
  private String tag = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("startingTrophies")
  private Integer startingTrophies = null;

  @SerializedName("trophyChange")
  private Integer trophyChange = null;

  @SerializedName("crowns")
  private Integer crowns = null;

  @SerializedName("clan")
  private ClanBase clan = null;

  @SerializedName("cards")
  private List<Object> cards = null;

  public BattleLogTeam tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @ApiModelProperty(value = "")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public BattleLogTeam name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BattleLogTeam startingTrophies(Integer startingTrophies) {
    this.startingTrophies = startingTrophies;
    return this;
  }

   /**
   * Get startingTrophies
   * @return startingTrophies
  **/
  @ApiModelProperty(value = "")
  public Integer getStartingTrophies() {
    return startingTrophies;
  }

  public void setStartingTrophies(Integer startingTrophies) {
    this.startingTrophies = startingTrophies;
  }

  public BattleLogTeam trophyChange(Integer trophyChange) {
    this.trophyChange = trophyChange;
    return this;
  }

   /**
   * Get trophyChange
   * @return trophyChange
  **/
  @ApiModelProperty(value = "")
  public Integer getTrophyChange() {
    return trophyChange;
  }

  public void setTrophyChange(Integer trophyChange) {
    this.trophyChange = trophyChange;
  }

  public BattleLogTeam crowns(Integer crowns) {
    this.crowns = crowns;
    return this;
  }

   /**
   * Get crowns
   * @return crowns
  **/
  @ApiModelProperty(value = "")
  public Integer getCrowns() {
    return crowns;
  }

  public void setCrowns(Integer crowns) {
    this.crowns = crowns;
  }

  public BattleLogTeam clan(ClanBase clan) {
    this.clan = clan;
    return this;
  }

   /**
   * Get clan
   * @return clan
  **/
  @ApiModelProperty(value = "")
  public ClanBase getClan() {
    return clan;
  }

  public void setClan(ClanBase clan) {
    this.clan = clan;
  }

  public BattleLogTeam cards(List<Object> cards) {
    this.cards = cards;
    return this;
  }

  public BattleLogTeam addCardsItem(Object cardsItem) {
    if (this.cards == null) {
      this.cards = new ArrayList<Object>();
    }
    this.cards.add(cardsItem);
    return this;
  }

   /**
   * Get cards
   * @return cards
  **/
  @ApiModelProperty(value = "")
  public List<Object> getCards() {
    return cards;
  }

  public void setCards(List<Object> cards) {
    this.cards = cards;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BattleLogTeam battleLogTeam = (BattleLogTeam) o;
    return Objects.equals(this.tag, battleLogTeam.tag) &&
        Objects.equals(this.name, battleLogTeam.name) &&
        Objects.equals(this.startingTrophies, battleLogTeam.startingTrophies) &&
        Objects.equals(this.trophyChange, battleLogTeam.trophyChange) &&
        Objects.equals(this.crowns, battleLogTeam.crowns) &&
        Objects.equals(this.clan, battleLogTeam.clan) &&
        Objects.equals(this.cards, battleLogTeam.cards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tag, name, startingTrophies, trophyChange, crowns, clan, cards);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BattleLogTeam {\n");
    
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    startingTrophies: ").append(toIndentedString(startingTrophies)).append("\n");
    sb.append("    trophyChange: ").append(toIndentedString(trophyChange)).append("\n");
    sb.append("    crowns: ").append(toIndentedString(crowns)).append("\n");
    sb.append("    clan: ").append(toIndentedString(clan)).append("\n");
    sb.append("    cards: ").append(toIndentedString(cards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

