/*
 * Clash Royale API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package crdiscordbot.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Clan
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-01-09T15:49:55.865Z")
public class Clan extends SearchResultClan {
  @SerializedName("description")
  private String description = null;

  @SerializedName("clanChestStatus")
  private String clanChestStatus = null;

  @SerializedName("clanChestPoints")
  private Integer clanChestPoints = null;

  @SerializedName("memberList")
  private List<ClanMember> memberList = null;

  public Clan description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Clan clanChestStatus(String clanChestStatus) {
    this.clanChestStatus = clanChestStatus;
    return this;
  }

   /**
   * Get clanChestStatus
   * @return clanChestStatus
  **/
  @ApiModelProperty(value = "")
  public String getClanChestStatus() {
    return clanChestStatus;
  }

  public void setClanChestStatus(String clanChestStatus) {
    this.clanChestStatus = clanChestStatus;
  }

  public Clan clanChestPoints(Integer clanChestPoints) {
    this.clanChestPoints = clanChestPoints;
    return this;
  }

   /**
   * Get clanChestPoints
   * @return clanChestPoints
  **/
  @ApiModelProperty(value = "")
  public Integer getClanChestPoints() {
    return clanChestPoints;
  }

  public void setClanChestPoints(Integer clanChestPoints) {
    this.clanChestPoints = clanChestPoints;
  }

  public Clan memberList(List<ClanMember> memberList) {
    this.memberList = memberList;
    return this;
  }

  public Clan addMemberListItem(ClanMember memberListItem) {
    if (this.memberList == null) {
      this.memberList = new ArrayList<ClanMember>();
    }
    this.memberList.add(memberListItem);
    return this;
  }

   /**
   * Get memberList
   * @return memberList
  **/
  @ApiModelProperty(value = "")
  public List<ClanMember> getMemberList() {
    return memberList;
  }

  public void setMemberList(List<ClanMember> memberList) {
    this.memberList = memberList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Clan clan = (Clan) o;
    return Objects.equals(this.description, clan.description) &&
        Objects.equals(this.clanChestStatus, clan.clanChestStatus) &&
        Objects.equals(this.clanChestPoints, clan.clanChestPoints) &&
        Objects.equals(this.memberList, clan.memberList) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, clanChestStatus, clanChestPoints, memberList, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Clan {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    clanChestStatus: ").append(toIndentedString(clanChestStatus)).append("\n");
    sb.append("    clanChestPoints: ").append(toIndentedString(clanChestPoints)).append("\n");
    sb.append("    memberList: ").append(toIndentedString(memberList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

