/*
 * Clash Royale API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package crdiscordbot.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ClanMember
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-01-09T15:49:55.865Z")
public class ClanMember extends PlayerBase {
  @SerializedName("role")
  private String role = null;

  @SerializedName("clanRank")
  private Integer clanRank = null;

  @SerializedName("previousClanRank")
  private Integer previousClanRank = null;

  @SerializedName("donations")
  private Integer donations = null;

  @SerializedName("donationsReceived")
  private Integer donationsReceived = null;

  @SerializedName("clanChestPoints")
  private Integer clanChestPoints = null;

  public ClanMember role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(value = "")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public ClanMember clanRank(Integer clanRank) {
    this.clanRank = clanRank;
    return this;
  }

   /**
   * Get clanRank
   * @return clanRank
  **/
  @ApiModelProperty(value = "")
  public Integer getClanRank() {
    return clanRank;
  }

  public void setClanRank(Integer clanRank) {
    this.clanRank = clanRank;
  }

  public ClanMember previousClanRank(Integer previousClanRank) {
    this.previousClanRank = previousClanRank;
    return this;
  }

   /**
   * Get previousClanRank
   * @return previousClanRank
  **/
  @ApiModelProperty(value = "")
  public Integer getPreviousClanRank() {
    return previousClanRank;
  }

  public void setPreviousClanRank(Integer previousClanRank) {
    this.previousClanRank = previousClanRank;
  }

  public ClanMember donations(Integer donations) {
    this.donations = donations;
    return this;
  }

   /**
   * Get donations
   * @return donations
  **/
  @ApiModelProperty(value = "")
  public Integer getDonations() {
    return donations;
  }

  public void setDonations(Integer donations) {
    this.donations = donations;
  }

  public ClanMember donationsReceived(Integer donationsReceived) {
    this.donationsReceived = donationsReceived;
    return this;
  }

   /**
   * Get donationsReceived
   * @return donationsReceived
  **/
  @ApiModelProperty(value = "")
  public Integer getDonationsReceived() {
    return donationsReceived;
  }

  public void setDonationsReceived(Integer donationsReceived) {
    this.donationsReceived = donationsReceived;
  }

  public ClanMember clanChestPoints(Integer clanChestPoints) {
    this.clanChestPoints = clanChestPoints;
    return this;
  }

   /**
   * Get clanChestPoints
   * @return clanChestPoints
  **/
  @ApiModelProperty(value = "")
  public Integer getClanChestPoints() {
    return clanChestPoints;
  }

  public void setClanChestPoints(Integer clanChestPoints) {
    this.clanChestPoints = clanChestPoints;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClanMember clanMember = (ClanMember) o;
    return Objects.equals(this.role, clanMember.role) &&
        Objects.equals(this.clanRank, clanMember.clanRank) &&
        Objects.equals(this.previousClanRank, clanMember.previousClanRank) &&
        Objects.equals(this.donations, clanMember.donations) &&
        Objects.equals(this.donationsReceived, clanMember.donationsReceived) &&
        Objects.equals(this.clanChestPoints, clanMember.clanChestPoints) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(role, clanRank, previousClanRank, donations, donationsReceived, clanChestPoints, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClanMember {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    clanRank: ").append(toIndentedString(clanRank)).append("\n");
    sb.append("    previousClanRank: ").append(toIndentedString(previousClanRank)).append("\n");
    sb.append("    donations: ").append(toIndentedString(donations)).append("\n");
    sb.append("    donationsReceived: ").append(toIndentedString(donationsReceived)).append("\n");
    sb.append("    clanChestPoints: ").append(toIndentedString(clanChestPoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

