/*
 * Clash Royale API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package crdiscordbot.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CurrentWar
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-01-09T15:49:55.865Z")
public class CurrentWar {
  @SerializedName("state")
  private String state = null;

  @SerializedName("warEndTime")
  private String warEndTime = null;

  @SerializedName("clan")
  private Object clan = null;

  @SerializedName("participants")
  private List<WarParticipant> participants = null;

  public CurrentWar state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public CurrentWar warEndTime(String warEndTime) {
    this.warEndTime = warEndTime;
    return this;
  }

   /**
   * Get warEndTime
   * @return warEndTime
  **/
  @ApiModelProperty(value = "")
  public String getWarEndTime() {
    return warEndTime;
  }

  public void setWarEndTime(String warEndTime) {
    this.warEndTime = warEndTime;
  }

  public CurrentWar clan(Object clan) {
    this.clan = clan;
    return this;
  }

   /**
   * Get clan
   * @return clan
  **/
  @ApiModelProperty(value = "")
  public Object getClan() {
    return clan;
  }

  public void setClan(Object clan) {
    this.clan = clan;
  }

  public CurrentWar participants(List<WarParticipant> participants) {
    this.participants = participants;
    return this;
  }

  public CurrentWar addParticipantsItem(WarParticipant participantsItem) {
    if (this.participants == null) {
      this.participants = new ArrayList<WarParticipant>();
    }
    this.participants.add(participantsItem);
    return this;
  }

   /**
   * Get participants
   * @return participants
  **/
  @ApiModelProperty(value = "")
  public List<WarParticipant> getParticipants() {
    return participants;
  }

  public void setParticipants(List<WarParticipant> participants) {
    this.participants = participants;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrentWar currentWar = (CurrentWar) o;
    return Objects.equals(this.state, currentWar.state) &&
        Objects.equals(this.warEndTime, currentWar.warEndTime) &&
        Objects.equals(this.clan, currentWar.clan) &&
        Objects.equals(this.participants, currentWar.participants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(state, warEndTime, clan, participants);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrentWar {\n");
    
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    warEndTime: ").append(toIndentedString(warEndTime)).append("\n");
    sb.append("    clan: ").append(toIndentedString(clan)).append("\n");
    sb.append("    participants: ").append(toIndentedString(participants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

