/*
 * Clash Royale API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package crdiscordbot.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * PlayerBase
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-01-09T15:49:55.865Z")
public class PlayerBase {
  @SerializedName("tag")
  private String tag = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("expLevel")
  private Integer expLevel = null;

  @SerializedName("trophies")
  private Integer trophies = null;

  @SerializedName("arena")
  private Arena arena = null;

  public PlayerBase tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @ApiModelProperty(value = "")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public PlayerBase name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PlayerBase expLevel(Integer expLevel) {
    this.expLevel = expLevel;
    return this;
  }

   /**
   * Get expLevel
   * @return expLevel
  **/
  @ApiModelProperty(value = "")
  public Integer getExpLevel() {
    return expLevel;
  }

  public void setExpLevel(Integer expLevel) {
    this.expLevel = expLevel;
  }

  public PlayerBase trophies(Integer trophies) {
    this.trophies = trophies;
    return this;
  }

   /**
   * Get trophies
   * @return trophies
  **/
  @ApiModelProperty(value = "")
  public Integer getTrophies() {
    return trophies;
  }

  public void setTrophies(Integer trophies) {
    this.trophies = trophies;
  }

  public PlayerBase arena(Arena arena) {
    this.arena = arena;
    return this;
  }

   /**
   * Get arena
   * @return arena
  **/
  @ApiModelProperty(value = "")
  public Arena getArena() {
    return arena;
  }

  public void setArena(Arena arena) {
    this.arena = arena;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerBase playerBase = (PlayerBase) o;
    return Objects.equals(this.tag, playerBase.tag) &&
        Objects.equals(this.name, playerBase.name) &&
        Objects.equals(this.expLevel, playerBase.expLevel) &&
        Objects.equals(this.trophies, playerBase.trophies) &&
        Objects.equals(this.arena, playerBase.arena);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tag, name, expLevel, trophies, arena);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerBase {\n");
    
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    expLevel: ").append(toIndentedString(expLevel)).append("\n");
    sb.append("    trophies: ").append(toIndentedString(trophies)).append("\n");
    sb.append("    arena: ").append(toIndentedString(arena)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

