/*
 * Clash Royale API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package crdiscordbot.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SeasonStatistics
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-01-09T15:49:55.865Z")
public class SeasonStatistics {
  @SerializedName("id")
  private String id = null;

  @SerializedName("trophies")
  private Integer trophies = null;

  @SerializedName("bestTrophies")
  private Integer bestTrophies = null;

  public SeasonStatistics id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SeasonStatistics trophies(Integer trophies) {
    this.trophies = trophies;
    return this;
  }

   /**
   * Get trophies
   * @return trophies
  **/
  @ApiModelProperty(value = "")
  public Integer getTrophies() {
    return trophies;
  }

  public void setTrophies(Integer trophies) {
    this.trophies = trophies;
  }

  public SeasonStatistics bestTrophies(Integer bestTrophies) {
    this.bestTrophies = bestTrophies;
    return this;
  }

   /**
   * Get bestTrophies
   * @return bestTrophies
  **/
  @ApiModelProperty(value = "")
  public Integer getBestTrophies() {
    return bestTrophies;
  }

  public void setBestTrophies(Integer bestTrophies) {
    this.bestTrophies = bestTrophies;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeasonStatistics seasonStatistics = (SeasonStatistics) o;
    return Objects.equals(this.id, seasonStatistics.id) &&
        Objects.equals(this.trophies, seasonStatistics.trophies) &&
        Objects.equals(this.bestTrophies, seasonStatistics.bestTrophies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, trophies, bestTrophies);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeasonStatistics {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    trophies: ").append(toIndentedString(trophies)).append("\n");
    sb.append("    bestTrophies: ").append(toIndentedString(bestTrophies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

