/*
 * Clash Royale API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package crdiscordbot.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Tournament
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-01-09T15:49:55.865Z")
public class Tournament extends TournamentBase {
  @SerializedName("startedTime")
  private String startedTime = null;

  @SerializedName("membersList")
  private List<Object> membersList = null;

  public Tournament startedTime(String startedTime) {
    this.startedTime = startedTime;
    return this;
  }

   /**
   * Get startedTime
   * @return startedTime
  **/
  @ApiModelProperty(value = "")
  public String getStartedTime() {
    return startedTime;
  }

  public void setStartedTime(String startedTime) {
    this.startedTime = startedTime;
  }

  public Tournament membersList(List<Object> membersList) {
    this.membersList = membersList;
    return this;
  }

  public Tournament addMembersListItem(Object membersListItem) {
    if (this.membersList == null) {
      this.membersList = new ArrayList<Object>();
    }
    this.membersList.add(membersListItem);
    return this;
  }

   /**
   * Get membersList
   * @return membersList
  **/
  @ApiModelProperty(value = "")
  public List<Object> getMembersList() {
    return membersList;
  }

  public void setMembersList(List<Object> membersList) {
    this.membersList = membersList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tournament tournament = (Tournament) o;
    return Objects.equals(this.startedTime, tournament.startedTime) &&
        Objects.equals(this.membersList, tournament.membersList) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startedTime, membersList, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tournament {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    startedTime: ").append(toIndentedString(startedTime)).append("\n");
    sb.append("    membersList: ").append(toIndentedString(membersList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

