name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -   
        name: Checkout
        uses: actions/checkout@v2
    -
        name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
         java-version: '21'
         distribution: 'temurin'
         cache: maven
    -
        name: Build and install discord4j-connect with Maven
        run: mvn -B package install --file connect/pom.xml
    - 
        name: Build with Maven
        run: mvn -B package --file pom.xml
    -   
        name: Build the worker Docker image
        run: docker build worker --tag crbot-worker:$(date +%s)
    -   
        name: Build the leader Docker image
        run: docker build leader --tag crbot-leader:$(date +%s)
    -
        name: Build with Maven
        run: mvn -B package --file connect-middleware/pom.xml
    -
        name: Build the connect-middleware Docker image
        run: docker build connect-middleware --tag crbot-connect-middleware:$(date +%s)
