name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -   
        name: Checkout
        uses: actions/checkout@v2
    -
        name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
         java-version: '11'
         distribution: 'adopt'
         cache: maven
    - 
        name: Build with Maven
        run: mvn -B package --file pom.xml
    -   
        name: Build the worker Docker image
        run: docker build crdiscordbot-worker --file Dockerfile --tag crbot-worker:$(date +%s)
    -   
        name: Build the leader Docker image
        run: docker build crdiscordbot-leader --file Dockerfile --tag crbot-leader:$(date +%s)
